name: portal
description: A sample command-line application.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  mockito: ^5.4.4
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.7
  lints: ^2.0.0
  test: ^1.24.6
